server:
  port: 8083
  servlet:
    context-path: /
# -------------------- Dubbo BEGIN --------------------
dubbo:
  registry:
    register: false
    address: zookeeper://localhost:2181
  application:
    name: userService-consumer
  provider:
    retries: 3
    timeout: 3000
# -------------------- Dubbo END --------------------
